Redesign to use DIVD style & template
DIVD-NL/SecurityMeldpunt pull request #6
Opened 2020-02-01 18:59 UTC by mrpapercut

2020-02-03 06:07 UTC, MrSeccubus requested changes
Zie comments in-line.

Paar algemene puntjes nog:
* Een H2 met een Hyperlink erin is niet herkenbaar als aanklikbaar
* De titel en subtitel in de banner veranderen mee met de titel van de pagina, ik zou deze graag over de site gelijk houden
* Op de homepage kun je nu gemakkelijk het menu over het hoofd zien, hierdoor lijkt het alsof je op de home page niet verder kun klikken.
* Tekst van /faq/40-headers/ klopt niet meer, we includen nu wel javascript, maar uitsluitend lokaal.

2020-02-03 06:07 UTC, MrSeccubus commented on .env
> +JEKYLL_GITHUB_TOKEN=
In GitIgnore heb je de directory .env toegevoegd, maar je hebt toch deze file ingechecked, Volgens mij is deze file niet nodig, toch?

2020-02-03 06:07 UTC, MrSeccubus commented on Dockerfile
> +
`EXPOSE 4000' toevoegen om port vrij te geven. ?

2020-02-03 06:07 UTC, MrSeccubus commented on _includes/navigation.html
> +    </ul>
Het origineel haalde de data op uit _data/navigation.yml kun je deze aanpassen zodat het hier niet hardcoded is?

2020-02-03 06:07 UTC, MrSeccubus commented
@mrpapercut ziet er erg mooi uit. Denk je wel. In mijn review had ik nog wat puntjes kun je daar naar kijken?

2020-02-05 18:26 UTC, mrpapercut commented on .env
> +JEKYLL_GITHUB_TOKEN=
Ik had die github_token variable nodig om Jekyll te laten draaien, vandaar. Dan check ik het bestand met lege values in, en zet ik het op .gitignore. De compose_project_name is een persoonlijke voorkeur, kan weg.
Maar als jij die github-token niet nodig hebt, dan kan je de waarde gewoon leeglaten.

2020-02-05 18:28 UTC, mrpapercut commented on Dockerfile
> +
Deze staat in docker-compose.yml

2020-02-05 20:16 UTC, mrpapercut commented on _includes/navigation.html
> +    </ul>
Aangepast in 49b4537

2020-02-05 20:20 UTC, mrpapercut commented
> Een H2 met een Hyperlink erin is niet herkenbaar als aanklikbaar
Ik heb deze titels een kleur gegeven

> De titel en subtitel in de banner veranderen mee met de titel van de pagina, ik zou deze graag over de site gelijk houden
Aangepast

> Op de homepage kun je nu gemakkelijk het menu over het hoofd zien, hierdoor lijkt het alsof je op de home page niet verder kun klikken.
Ja, dit vind ik ook, maar zo zit het in het thema. Chris heeft het opgelost met links op de homepagina. Ik zou aanraden ook zoiets te doen.

> Tekst van /faq/40-headers/ klopt niet meer, we includen nu wel javascript, maar uitsluitend lokaal.
Nou ja, feitelijk klopt het nog steeds. Javascript maakt het niet minder statisch, en we laden nog steeds geen externe resources in

Ik kreeg conflicten met m'n nieuwe commits, dus nu is de lijst dubbel. Misschien even kijken of ik een nieuwe pull request aanmaak

2020-02-07 09:37 UTC, MrSeccubus commented on .env
> +JEKYLL_GITHUB_TOKEN=
Tjek

2020-02-07 11:11 UTC, merged