case add mirai
DIVD-NL/SecurityMeldpunt pull request #8
Opened 2020-02-07 13:47 UTC by spierenburg

2020-02-07 14:00 UTC, MrSeccubus requested changes
@spierenburg ik heb het Nederlandse stuje even gereviewed. Ziet er goed uit, schrik niet van het aantal comments, ik zit altijd zo te zeiken ;)

Het ENgelse stukje moet uiteraard op dezelfde manier aangepast worden.

2020-02-07 14:00 UTC, MrSeccubus commented on cases/DIVD-2020-00004.md
> +excerpt: A list of Mirai botnet victims has been published exposing a total of 500K+ systems
Excerpt in NL / EN

2020-02-07 14:00 UTC, MrSeccubus commented on cases/DIVD-2020-00004.md
> +| Recommendation | Upgrade to secure shell and harden systems |
Is het advies niet eerder: Make sure these systems are taken off line?

2020-02-07 14:00 UTC, MrSeccubus commented on cases/DIVD-2020-00004.md
> +Er is een grote waarschijnlijkheid dat deze systemen opnieuw misbruikt gaan worden door kwaadwillenden en we willen met deze case een poging doen om de Nederlandse eigenaren te bereiken.
En de reeds gehackte en nog steeds kwetsbare systemen offline halen.

2020-02-07 14:00 UTC, MrSeccubus commented on cases/DIVD-2020-00004.md
> +Artikel met informatie over de gepubliceerde lijst (in het engels): https://www.zdnet.com/article/hacker-leaks-passwords-for-more-than-500000-servers-routers-and-iot-devices/
Link format `[https://www.zdnet.com/article/hacker-leaks-passwords-for-more-than-500000-servers-routers-and-iot-devices/](https://www.zdnet.com/article/hacker-leaks-passwords-for-more-than-500000-servers-routers-and-iot-devices/)`

2020-02-07 14:00 UTC, MrSeccubus commented on cases/DIVD-2020-00004.md
> +We raden iedereen aan de volgende overweging te maken:
Controleer of de systemen nog online staat, inden dit zo is ga er dan van uit dat dit systeem is overgenomen door hackers.

2020-02-07 14:00 UTC, MrSeccubus commented on cases/DIVD-2020-00004.md
> +Wij zijn op dit moment bezig de gepubliceerde lijst met systemen te controleren en gaan proberen slachtoffers te bereiken.
wij gaan de systeem eigenaren via hun netwerkbeheerder informeren.

2020-02-07 14:00 UTC, MrSeccubus commented on cases/DIVD-2020-00004.md
> +| 20-1-2020 | Security Meldpunt heeft een lijst ontvangen van 2730 nederlandse IP adressen
| ? -1-202 | Een lijst met Mirai "sclachtoffers wordt door een DoS Booter website gepubliceerd |

2020-02-07 14:19 UTC, spierenburg commented on cases/DIVD-2020-00004.md
> +| Recommendation | Upgrade to secure shell and harden systems |
ja prima

2020-02-10 09:31 UTC, MrSeccubus commented
Closed by mistake.

2020-02-10 09:35 UTC, MrSeccubus approved these changes

2020-02-10 13:14 UTC, merged